version: "3"
services:
  react-app:
    image: simple-react-app:0.1
    container_name: react-app
    environment:
      #- REACT_APP_API_HOST=python-api
      #- REACT_APP_API_PORT=5000
      - REACT_APP_API_HOST=127.0.0.1
      - REACT_APP_API_PORT=8000
      - DEBUG=simplereact
    ports:
      - 5000:3000
    stdin_open: true
    depends_on:
      - python-api

  python-api:
    image: simple-api:0.1
    container_name: python_api
    environment:
     - MONGO_HOST=mongo
     - MONGO_PORT=27017
     - MONGO_USER=admin
     - MONGO_PASSWD=passwd
    ports:
      - 8000:5000
    restart: on-failure
    depends_on:
      - mongo

  mongo:
    image: mongo
    container_name: py-mongo
    environment:
     - MONGO_INITDB_ROOT_USERNAME=admin
     - MONGO_INITDB_ROOT_PASSWORD=passwd
    ports:
      - 27018:27017
    volumes:
      - ./mongo-data/mongo:/data/db
