version: '2'
services:
  simple-app:
    image: simple-react-app
    container_name: react-app
    environment:
      - TZ=Asia/Kolkata
      - REACT_APP_API_HOST=192.168.0.109
      - REACT_APP_API_PORT=8000
      - DEBUG=simplereact
    ports:
      - 5000:3000
    stdin_open: true
